# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolaySiparisApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant_promos',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
