# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolaySiparisApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
