# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolaySiparisApp', '0002_restaurant_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
