# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('KolaySiparisApp', '0002_restaurant_restaurant_promos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KolaySiparisApp.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('menu', models.ManyToManyField(to='KolaySiparisApp.Menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KolaySiparisApp.Restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant_promos',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KolaySiparisApp.Restaurant'),
        ),
        migrations.AddField(
            model_name='customer_orders',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='KolaySiparisApp.Order'),
        ),
    ]
