# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KolaySiparisApp', '0004_order_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
